services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5286:3000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
