services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5286"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
